image: node:10.6.0

stages:
  - build
 

cache:
  paths:
    - node_modules/

build site:
  stage: build
  script:
    - cd client
    - npm install --progress=false
    - npm install nodemon@latest -D
    - npm run unit
